Completed prep-Javascript-variables
Nathan-Chon/lfz-prep-0123-code-solutions pull request #10
Opened 2023-01-16 05:25 UTC by Nathan-Chon

![Screenshot_20230115_092312](https://user-images.githubusercontent.com/121650766/212604610-03cab8b7-8a20-4566-831c-a0e2c93dd3cc.png)

2023-01-16 18:03 UTC, Zhiwutian requested changes
small update needed

2023-01-16 18:03 UTC, BrettAlbright commented on prep-javascript-variables/index.html
> +    var NumberOfPets = 1;
only special variables should start with capital letters. I would change this to a lowercase n

2023-01-16 20:59 UTC, Nathan-Chon commented
![Screenshot_20230116_125706](https://user-images.githubusercontent.com/121650766/212764816-fa121ad3-14a5-43bb-929a-f12bfdc50d3c.png)
fixed capitalization problem

2023-01-17 18:30 UTC, Zhiwutian approved these changes
👍🏼

2023-01-18 00:34 UTC, merged