prep-css-box-model Nathan Chon
Nathan-Chon/lfz-prep-0123-code-solutions pull request #6
Opened 2023-01-11 08:14 UTC by Nathan-Chon

![Screenshot_20230111_121238](https://user-images.githubusercontent.com/121650766/211752897-0b709914-9718-403a-89d8-339c0a72f31c.png)

2023-01-11 18:41 UTC, Zhiwutian requested changes
Looking good so far, just make sure to update the padding to be on all four sides

2023-01-11 18:41 UTC, Zhiwutian commented on prep-css-box-model/styles.css
> +  padding-top: 10px;
you want padding on all sides not just the top

2023-01-12 09:59 UTC, Nathan-Chon commented
![Screenshot_20230112_015536](https://user-images.githubusercontent.com/121650766/212036388-ce281c27-8330-407c-aa5c-f33acb586176.png)

"revised padding of code"

2023-01-13 20:19 UTC, Zhiwutian approved these changes
👍🏼

2023-01-14 00:48 UTC, merged